contact_links
  - name: Contact Us
    url: https://scratch.mit.edu/discuss/topic/364975/
    about: Please contact our workers here.
  - name: Contact Lead Developer
    url: https://scratch.mit.edu/users/Nambaseking01
    about: Please contact the lead developer here.
